export const VegetableFruits = [
    {
      id: 1,
      title: "Capsicum",
      img: "src/images/Capsicum.jpg",
      price: 50,
      info: "Fresh frpom the farms .",
      inCart: false,
      count: 0,
      total: 0,
    },
    {
        id: 2,
        title: "Cabbage",
        img: "src/images/Cabbage.jpg",
        price: 20,
        info: "Fresh from the farms",
        inCart: false,
        count: 0,
        total: 0,
      },
      {
        id: 3,
        title: "Carrot",
        img: "src/images/Carrot.jpg",
        price: 30,
        info: "Fresh from the farms",
        inCart: false,
        count: 0,
        total: 0,
      },
      {
        id: 4,
        title: "Brinjal",
        img: "src/images/Brinjal.jpg",
        price: 40,
        info: "Fresh from the farms",
        inCart: false,
        count: 0,
        total: 0,
      },
      {
        id: 5,
        title: "Tomato",
        img: "src/images/Tomato.jpg",
        price: 30,
        info: "Fresh from the farms",
        inCart: false,
        count: 0,
        total: 0,
      },
      {
        id: 6,
        title: "Apple",
        img: "src/images/Apple.jpg",
        price: 60,
        info: "Fresh from the farms",
        inCart: false,
        count: 0,
        total: 0,
      },
      {
        id: 7,
        title: "Mango",
        img: "src/images/Apple.jpg",
        price: 60,
        info: "Fresh from the farms",
        inCart: false,
        count: 0,
        total: 0,
      },


]